# Generated by Django 5.2.5 on 2026-03-13 18:24

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0004_bookbookmark_book_is_featured_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "knowledge_domain",
                    models.CharField(
                        choices=[
                            ("Religious Knowledge", "Religious Knowledge"),
                            ("Islamic Sciences", "Islamic Sciences"),
                        ],
                        default="Religious Knowledge",
                        max_length=50,
                    ),
                ),
                ("cover_image", models.ImageField(upload_to="blog/covers/%Y/%m/")),
                (
                    "short_description",
                    models.TextField(
                        help_text="A brief summary for the listing page.",
                        max_length=500,
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_articles",
                        to="library.scholar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholar Biography",
                "verbose_name_plural": "Scholar Biographies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScholarArticleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.scholararticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
