# Generated by Django 5.2.5 on 2026-03-13 18:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholararticle",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
