# Generated by Django 5.2.5 on 2026-03-13 18:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_scholararticle_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholararticle",
            name="cover_image",
            field=models.ImageField(upload_to=blog.models.scholar_cover_upload),
        ),
    ]
