# Generated by Django 5.2.5 on 2026-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_scholararticle_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholararticle",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
